# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build App and Test

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'release/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Set up JDK 11
        uses: actions/setup-java@v3.5.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@2.4.2
        with:
          gradle-version: 7.6.1
          arguments: test